env = Environment(tools = ['default', 'compilation_db'])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

godot_cpp_path = "godot-cpp"

env.Append(CXXFLAGS=['-std=c++26'])

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/", "tests/"])
env.Append(CPPPATH=["src/chart"])
env.Append(CPPPATH=[godot_cpp_path + "/include", godot_cpp_path + "/gen/include"])
env.Append(LIBPATH=[godot_cpp_path + "/bin"])
env.Append(LIBS=["libgodot-cpp.macos.template_debug.universal"])

debug_mode = ARGUMENTS.get('debug', 0)

if int(debug_mode):
    env.Append(CCFLAGS = ['-g', '-O0'])

sources = [
    Glob("src/*.cpp"),
    Glob("src/Memory/*.cpp"),
    Glob("src/Scripts/*.cpp"),
    Glob("src/Level/*.cpp"),
    Glob("src/Math/*.cpp")
]

lib_filename = "tri64"
library = env.SharedLibrary(
    target="../project/bin/{}".format(lib_filename),
    source=sources,
)

test_sources = [Glob("tests/*.cpp"), Glob("tests/LevelScript/*.cpp"), library]

test = env.Program(
    target="tests/bin/test",
    source=test_sources
)

compilation_database = env.CompilationDatabase('compile_commands.json', library)

Default([library, compilation_database])

env.Alias('test', [test, compilation_database])
